### ISSUE TITLE
Exposing options to button scope

### ISSUE THREAD

**Issue by Luuccc** [bitfocus/companion-module-base#52]
While developing a module for Companion 3, I was looking to allow the user to quickly display (as a Button text string) the currently entered/selected input field value of a specific Action/Feedback on a Button.

For example, a user has created a Button with an Acton that enables/disables some line-in. This specific line-in that's controlled might be specified by a number input field e.g. Disable Line: 4. 

Instead of the user needing to type this in manually each time, it might be useful if you could access a Button's local scope through internal variables with something along the lines of `${this:audio_mixer.disableline.lineIn}`, which would equal the current input field value of the lineIn being disabled. This would always equal the lineIn being effected, updating the button text automatically.

In the case that the user had the same Action multiple times, it might be useful to specify which of the multiple Actions you would like to display the input field of, with an index property like ${this:audio_mixer.disableline.lineIn#2}`

**Comment by dnmeid** [comment]
related/duplicate issue: https://github.com/bitfocus/companion/issues/1909
I close this one and add your additional request there.
