### ISSUE TITLE
Make options optional

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion-module-base#53]
Sort of similar to #47 it would be nice if the options field was optional in action config source code. Currently it throws an error because it's trying to do a map on an undefined value.

Likewise with presets for options and feedbacks.

Also I think anywhere serializeIsVisibleFn is called.

**Comment by Julusian** [comment]
I have left the typings as saying these fields are required as I think it is a good practise for clarity to have them set, but the code should now handle them being missing

**Comment by peternewman** [comment]
Thanks @Julusian . I've also opened https://github.com/bitfocus/companion/pull/2558 to fix another related issue.

> I have left the typings as saying these fields are required as I think it is a good practise for clarity to have them set, but the code should now handle them being missing

I'm assuming from that you don't really want people going round removing or omitting them then ideally?

Thanks anyway, it should make developing things more user-friendly anyway.
