### ISSUE TITLE
Request: Allow more flexible Bonjour queries

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-base#87]
Picking up from [this conversation](https://bitfocusio.slack.com/archives/CFG7HAN5N/p1722308862286739) on slack.

I would like to be able to make Bonjour queries that accept an array of values for a TXT field, combined with an OR. Such as:

```
 "txt": {
 	"Model": ["EM6000", "L6000"]
}
```

@Julusian  alternatively suggested accepting an array of queries, which would be a more flexible but more verbose approach:

> There isn't a way to do this currently. But I suppose it could be made so that the whole query can be either one or an array of queries.
> It's more verbose than you would like, but keeps it simpler and flexible.
> It won't be the easiest change to make though
> Or maybe what you have proposed here wouldn't be too bad, I don't remember how/where the txt filtering is done

**Comment by Julusian** [comment]
This will be supported in 1.10.0 of this library. Its implemented and working, until the library is released it is not ready for modules to use

**Comment by phillipivan** [comment]
Thanks Julian. Did you make any progress with the parsing of differently structured Bonjour announcements? Should I create an issue for that?

**Comment by Julusian** [comment]
I haven't looked into that yet. An issue in the main companion repository might be a good idea as a reminder for myself

**Comment by phillipivan** [comment]
Done.
https://github.com/bitfocus/companion/issues/2993
