### ISSUE TITLE
WIKI Update

### ISSUE THREAD

**Issue by joezimjs** [bitfocus/companion-module-base#91]
There's a part on the home page of the wiki that says "If you are making a new module, then clone the boilerplate to an appropriately named folder". For a long time I couldn't get this to work because I thought "the boilerplate" referred to this repo rather than https://github.com/bitfocus/companion-module-template-js. Please turn "the boilerplate" into a link to that repo so there's no more confusion.

**Comment by bryce-seifert** [comment]
Added links for the js and ts templates to the wiki!
https://github.com/bitfocus/companion-module-base/wiki#4-clone-the-module
