### ISSUE TITLE
Handle action callback returns

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-base#96]
At the moment companion ignores (as far as I can tell) any returned value from the action callback. I would like to see it handle these, in a binary `success | fail` manner for two reasons:

- Users could then have the option of setting relative delays to occur after an action starts or completes (for async callbacks which may take appreciable time to complete). Similar to the difference between Qlab's auto-follow and auto-continue logic.
- Users could then have the option to interrupt a sequence of actions (or perhaps specify an alternate action sequence) on action failure.

Perhaps this should be in the breaking changes section, not sure.

**Comment by Julusian** [comment]
Companion does handle errors, but just so far as logging them.

This sounds like ideas proposed in https://github.com/bitfocus/companion/issues/2882

At one point I was wondering if we should allow modules to return a value, which the user would be able to select a custom variable to store the value into. This would be more powerful when 'local variables' are more of a thing, to be able to use in later actions easily.
This was motivated by the generic-http module which does this and has a hacky flow for it currently.
