### ISSUE TITLE
Enhance logging wiki page to explain different logs

### ISSUE THREAD

**Issue by howartp84** [bitfocus/companion-module-base#97]
(I'm not sure how to propose updates to wiki; if there's a better place please say so)

### Summary
Logs are available in:
- Admin UI
- Connection panel > 3 dots > View logs
- Local filesystem in C:\Users\username\AppData\Roaming\companion\logs 

### Issue
Being new to this community I got stuck at the first hurdle with updating a module as the copy of my module in companion-module-dev wouldn't start.

https://github.com/bitfocus/companion-module-base/wiki/Logging mentions about how to write to the Admin UI log during development but it mentions nothing about the connection logs accessed by the 3 dots > "View logs" button in the connection panel, which are required when your connection module won't even start (due to a JSON issue).

Nor does it tell you where to find or access the companion-yyyy-mm-dd.log file which confirms what modules have been found and located in companion-module-dev (C:\Users\username\AppData\Roaming\companion\logs on Windows; not sure on other OS's).

As an experienced developer by night, and IT support/manager by day, but being new to this community, I was pulling my hair out a the lack of logs telling me what was up - it turns out they exist in three places, but I could only find reference to one of them.  I had to seek help on Slack to even know the other two existed, never mind find them.

Could the logging wiki page be expanded?

**Comment by bryce-seifert** [comment]
@howartp84 I've made some updates to the logging page, let me know if you think I'm missing anything, or and thing still reads as confusing.

**Comment by howartp84** [comment]
Thank you - that's very helpful.

Peter
