### ISSUE TITLE
Allow fetching the value of a custom variable

### ISSUE THREAD

**Issue by Xentox-Phil** [bitfocus/companion-module-base#99]
I defined the options for the Action as the following

```typescript
{
		id: 'aCustomVar',
		type: 'custom-variable',
		label: 'Please set a custom var so i can get the value! ^^',
}
```

```typescript
const aCustomVar = self.getVariableValue(event.options.aCustomVar as string) as number
```

but when i tried this this did not work i got undefined back...

only variables of the module could be accessed

**Comment by Julusian** [comment]
I would advise that modules shouldn't really be aware of custom variables, just generally variables.
That `custom-variable` field type is an experimental flow specifically to allow the `generic-http` and related modules to output values when executing actions.

Instead, use a `textinput` field, with `useVariables: true`, then use `parseVariablesInString(event.options.something)` to parse that into a real string.
Then the user can define a string which can include any number of variables
